# Generated by Django 6.0.7 on 2026-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('job_seeker', 'job_seeker'), ('recruiter', 'recruiter')], default='job_seeker', max_length=20),
        ),
    ]
